stages:
  - lint

variables:
  PYTHON_VERSION: "3.10"

before_script:
  - python3 -m pip install --upgrade pip
  - pip install flake8

lint:
  stage: lint
  script:
    - flake8 .

  variables:
    FLAKE8_MAX_COMPLEXITY: 10
    FLAKE8_MAX_LINE_LENGTH: 88

  allow_failure: false

  script:
    - flake8 --max-line-length=88 --max-complexity=10 .
